from datetime import datetime
from typing import TYPE_CHECKING
from sqlalchemy import Column, String, DateTime, Text, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship
import uuid

from src.db.database import Base

if TYPE_CHECKING:
    from .user_query import UserQuery  # noqa: F401
    from .source_citation import SourceCitation  # noqa: F401


class ChatbotAnswer(Base):
    """
    Model representing the response generated by the LLM, grounded in retrieved textbook content
    """
    __tablename__ = "chatbot_answers"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_query_id = Column(UUID(as_uuid=True), ForeignKey("user_queries.id"), nullable=False)
    answer_text = Column(Text, nullable=False)  # The generated answer
    timestamp = Column(DateTime, nullable=False, default=datetime.utcnow)  # Time of the answer
    language = Column(String, nullable=False, default="en")  # Language of the answer
    llm_model = Column(String, nullable=False)  # Name of the LLM model used
    embedding_model = Column(String, nullable=False)  # Name of the embedding model used

    # Relationship with UserQuery
    user_query = relationship("UserQuery", back_populates="chatbot_answer")
    
    # Relationship with SourceCitation
    citations = relationship("SourceCitation", back_populates="chatbot_answer")